export { default as icon_list } from './icon-list-json.json';
import icon_add from './src/components/icon-add.vue';
import icon_B from './src/components/icon-B.vue';
import icon_batch_choice from './src/components/icon-batch-choice.vue';
import icon_callback from './src/components/icon-callback.vue';
import icon_classify from './src/components/icon-classify.vue';
import icon_close_block from './src/components/icon-close-block.vue';
import icon_close_eye_block from './src/components/icon-close-eye-block.vue';
import icon_close_eye from './src/components/icon-close-eye.vue';
import icon_close_ring from './src/components/icon-close-ring.vue';
import icon_close from './src/components/icon-close.vue';
import icon_code from './src/components/icon-code.vue';
import icon_color_block from './src/components/icon-color-block.vue';
import icon_component from './src/components/icon-component.vue';
import icon_contraction from './src/components/icon-contraction.vue';
import icon_copy_block from './src/components/icon-copy-block.vue';
import icon_copy from './src/components/icon-copy.vue';
import icon_delete_block from './src/components/icon-delete-block.vue';
import icon_delete from './src/components/icon-delete.vue';
import icon_down_block from './src/components/icon-down-block.vue';
import icon_down from './src/components/icon-down.vue';
import icon_download_ring from './src/components/icon-download-ring.vue';
import icon_download from './src/components/icon-download.vue';
import icon_drawing_board from './src/components/icon-drawing-board.vue';
import icon_edit_block_ring from './src/components/icon-edit-block-ring.vue';
import icon_edit from './src/components/icon-edit.vue';
import icon_exclamation_point_block from './src/components/icon-exclamation-point-block.vue';
import icon_exclamation_point_ring from './src/components/icon-exclamation-point-ring.vue';
import icon_eye_block from './src/components/icon-eye-block.vue';
import icon_eye from './src/components/icon-eye.vue';
import icon_fallback from './src/components/icon-fallback.vue';
import icon_filtrate from './src/components/icon-filtrate.vue';
import icon_folder_block from './src/components/icon-folder-block.vue';
import icon_folder from './src/components/icon-folder.vue';
import icon_full_seen from './src/components/icon-full-seen.vue';
import icon_gear_block from './src/components/icon-gear-block.vue';
import icon_gear from './src/components/icon-gear.vue';
import icon_gohome from './src/components/icon-gohome.vue';
import icon_I from './src/components/icon-I.vue';
import icon_image from './src/components/icon-image.vue';
import icon_info_block from './src/components/icon-info-block.vue';
import icon_info_ring from './src/components/icon-info-ring.vue';
import icon_left_block from './src/components/icon-left-block.vue';
import icon_left_double from './src/components/icon-left-double.vue';
import icon_left from './src/components/icon-left.vue';
import icon_letter_block from './src/components/icon-letter-block.vue';
import icon_loading from './src/components/icon-loading.vue';
import icon_message_black from './src/components/icon-message-black.vue';
import icon_message_block_point from './src/components/icon-message-block-point.vue';
import icon_message_point from './src/components/icon-message-point.vue';
import icon_message from './src/components/icon-message.vue';
import icon_minus from './src/components/icon-minus.vue';
import icon_mobile from './src/components/icon-mobile.vue';
import icon_notice_block from './src/components/icon-notice-block.vue';
import icon_notice from './src/components/icon-notice.vue';
import icon_ok_block from './src/components/icon-ok-block.vue';
import icon_ok_ring from './src/components/icon-ok-ring.vue';
import icon_ok from './src/components/icon-ok.vue';
import icon_page_block from './src/components/icon-page-block.vue';
import icon_page from './src/components/icon-page.vue';
import icon_pc from './src/components/icon-pc.vue';
import icon_plus from './src/components/icon-plus.vue';
import icon_point from './src/components/icon-point.vue';
import icon_position_block from './src/components/icon-position-block.vue';
import icon_position from './src/components/icon-position.vue';
import icon_put_away from './src/components/icon-put-away.vue';
import icon_question_mark_ring from './src/components/icon-question-mark-ring.vue';
import icon_right_block from './src/components/icon-right-block.vue';
import icon_right_double from './src/components/icon-right-double.vue';
import icon_right from './src/components/icon-right.vue';
import icon_search from './src/components/icon-search.vue';
import icon_seave_ring from './src/components/icon-seave-ring.vue';
import icon_set_block from './src/components/icon-set-block.vue';
import icon_set from './src/components/icon-set.vue';
import icon_share_other from './src/components/icon-share-other.vue';
import icon_share from './src/components/icon-share.vue';
import icon_sort_down from './src/components/icon-sort-down.vue';
import icon_sort_up from './src/components/icon-sort-up.vue';
import icon_sort from './src/components/icon-sort.vue';
import icon_stretch from './src/components/icon-stretch.vue';
import icon_switch_down_r from './src/components/icon-switch-down-r.vue';
import icon_switch_down from './src/components/icon-switch-down.vue';
import icon_switch_left_double from './src/components/icon-switch-left-double.vue';
import icon_switch_left from './src/components/icon-switch-left.vue';
import icon_switch_right_double from './src/components/icon-switch-right-double.vue';
import icon_switch_right from './src/components/icon-switch-right.vue';
import icon_switch_up_r from './src/components/icon-switch-up-r.vue';
import icon_switch_up from './src/components/icon-switch-up.vue';
import icon_switch from './src/components/icon-switch.vue';
import icon_txt from './src/components/icon-txt.vue';
import icon_U from './src/components/icon-U.vue';
import icon_up_block from './src/components/icon-up-block.vue';
import icon_up from './src/components/icon-up.vue';
import icon_upload_cloud from './src/components/icon-upload-cloud.vue';
import icon_upload_ring from './src/components/icon-upload-ring.vue';
import icon_upload from './src/components/icon-upload.vue';
import icon_user from './src/components/icon-user.vue';

const Ions = {
  install: (app, options) => {
    app.component(icon_add.name, icon_add);
app.component(icon_B.name, icon_B);
app.component(icon_batch_choice.name, icon_batch_choice);
app.component(icon_callback.name, icon_callback);
app.component(icon_classify.name, icon_classify);
app.component(icon_close_block.name, icon_close_block);
app.component(icon_close_eye_block.name, icon_close_eye_block);
app.component(icon_close_eye.name, icon_close_eye);
app.component(icon_close_ring.name, icon_close_ring);
app.component(icon_close.name, icon_close);
app.component(icon_code.name, icon_code);
app.component(icon_color_block.name, icon_color_block);
app.component(icon_component.name, icon_component);
app.component(icon_contraction.name, icon_contraction);
app.component(icon_copy_block.name, icon_copy_block);
app.component(icon_copy.name, icon_copy);
app.component(icon_delete_block.name, icon_delete_block);
app.component(icon_delete.name, icon_delete);
app.component(icon_down_block.name, icon_down_block);
app.component(icon_down.name, icon_down);
app.component(icon_download_ring.name, icon_download_ring);
app.component(icon_download.name, icon_download);
app.component(icon_drawing_board.name, icon_drawing_board);
app.component(icon_edit_block_ring.name, icon_edit_block_ring);
app.component(icon_edit.name, icon_edit);
app.component(icon_exclamation_point_block.name, icon_exclamation_point_block);
app.component(icon_exclamation_point_ring.name, icon_exclamation_point_ring);
app.component(icon_eye_block.name, icon_eye_block);
app.component(icon_eye.name, icon_eye);
app.component(icon_fallback.name, icon_fallback);
app.component(icon_filtrate.name, icon_filtrate);
app.component(icon_folder_block.name, icon_folder_block);
app.component(icon_folder.name, icon_folder);
app.component(icon_full_seen.name, icon_full_seen);
app.component(icon_gear_block.name, icon_gear_block);
app.component(icon_gear.name, icon_gear);
app.component(icon_gohome.name, icon_gohome);
app.component(icon_I.name, icon_I);
app.component(icon_image.name, icon_image);
app.component(icon_info_block.name, icon_info_block);
app.component(icon_info_ring.name, icon_info_ring);
app.component(icon_left_block.name, icon_left_block);
app.component(icon_left_double.name, icon_left_double);
app.component(icon_left.name, icon_left);
app.component(icon_letter_block.name, icon_letter_block);
app.component(icon_loading.name, icon_loading);
app.component(icon_message_black.name, icon_message_black);
app.component(icon_message_block_point.name, icon_message_block_point);
app.component(icon_message_point.name, icon_message_point);
app.component(icon_message.name, icon_message);
app.component(icon_minus.name, icon_minus);
app.component(icon_mobile.name, icon_mobile);
app.component(icon_notice_block.name, icon_notice_block);
app.component(icon_notice.name, icon_notice);
app.component(icon_ok_block.name, icon_ok_block);
app.component(icon_ok_ring.name, icon_ok_ring);
app.component(icon_ok.name, icon_ok);
app.component(icon_page_block.name, icon_page_block);
app.component(icon_page.name, icon_page);
app.component(icon_pc.name, icon_pc);
app.component(icon_plus.name, icon_plus);
app.component(icon_point.name, icon_point);
app.component(icon_position_block.name, icon_position_block);
app.component(icon_position.name, icon_position);
app.component(icon_put_away.name, icon_put_away);
app.component(icon_question_mark_ring.name, icon_question_mark_ring);
app.component(icon_right_block.name, icon_right_block);
app.component(icon_right_double.name, icon_right_double);
app.component(icon_right.name, icon_right);
app.component(icon_search.name, icon_search);
app.component(icon_seave_ring.name, icon_seave_ring);
app.component(icon_set_block.name, icon_set_block);
app.component(icon_set.name, icon_set);
app.component(icon_share_other.name, icon_share_other);
app.component(icon_share.name, icon_share);
app.component(icon_sort_down.name, icon_sort_down);
app.component(icon_sort_up.name, icon_sort_up);
app.component(icon_sort.name, icon_sort);
app.component(icon_stretch.name, icon_stretch);
app.component(icon_switch_down_r.name, icon_switch_down_r);
app.component(icon_switch_down.name, icon_switch_down);
app.component(icon_switch_left_double.name, icon_switch_left_double);
app.component(icon_switch_left.name, icon_switch_left);
app.component(icon_switch_right_double.name, icon_switch_right_double);
app.component(icon_switch_right.name, icon_switch_right);
app.component(icon_switch_up_r.name, icon_switch_up_r);
app.component(icon_switch_up.name, icon_switch_up);
app.component(icon_switch.name, icon_switch);
app.component(icon_txt.name, icon_txt);
app.component(icon_U.name, icon_U);
app.component(icon_up_block.name, icon_up_block);
app.component(icon_up.name, icon_up);
app.component(icon_upload_cloud.name, icon_upload_cloud);
app.component(icon_upload_ring.name, icon_upload_ring);
app.component(icon_upload.name, icon_upload);
app.component(icon_user.name, icon_user);

  }
};

export default Ions;
